### ISSUE TITLE
Error while trying to curl the files 

### ISSUE THREAD

**Issue by Shashi456** [abesmon/SwiftWinDemo#1]
Sometimes the VC prompt fales to identify the ```%VCToolsInstallDir%``` variable.
```

curl -L "https://raw.githubusercontent.com/apple/swift/master/stdlib/public/Platform/visualc.apinotes" -o "\include\visualc.apinotes"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file \include\visualc.apinotes: No such file or
Warning: directory
100   154  100   154    0     0    154      0  0:00:01 --:--:--  0:00:01   980
curl: (23) Failed writing body (0 != 154)
```

Could you add a note saying : If `VCToolsInstallDir `doesn't work, people can use `VCInstallDir `or `VCToolsVersion`

**Comment by Shashi456** [comment]
Also i get this error 
``````
curl -L "https://raw.githubusercontent.com/apple/swift/master/stdlib/public/Platform/winsdk.modulemap" -o "C:\Program Files (x86)\Windows Kits\10\\Include\10.0.10240.0\um\module.modulemap"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file C:\Program Files (x86)\Windows
Warning: Kits\10\\Include\10.0.10240.0\um\module.modulemap: No such file or
Warning: directory
100  2673  100  2673    0     0   2673      0  0:00:01 --:--:--  0:00:01 17134
curl: (23) Failed writing body (0 != 2673) 
``````


When i did check if there was a um directory, there isn't. Adding it manually didn't help the case either. Any idea?

**Comment by Shashi456** [comment]
I found the error there, Is there supposed to be an um directory in the 10.0.10240.0 or is it supposed to be within the ucrt directory?

**Comment by abesmon** [comment]
@Shashi456 thanks for issue report. Have you resolve the issue? And if you do, can you describe what you've done and how have your resolve it? :) I think, that could be helpful for someone :)

**Comment by abesmon** [comment]
> Also i get this error
> 
> ```
> curl -L "https://raw.githubusercontent.com/apple/swift/master/stdlib/public/Platform/winsdk.modulemap" -o "C:\Program Files (x86)\Windows Kits\10\\Include\10.0.10240.0\um\module.modulemap"
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file C:\Program Files (x86)\Windows
> Warning: Kits\10\\Include\10.0.10240.0\um\module.modulemap: No such file or
> Warning: directory
> 100  2673  100  2673    0     0   2673      0  0:00:01 --:--:--  0:00:01 17134
> curl: (23) Failed writing body (0 != 2673) 
> ```
> When i did check if there was a um directory, there isn't. Adding it manually didn't help the case either. Any idea?

The issue here, as I can see is that %UCRTVersion% have not resolved.

Also about replacing `VCToolsInstallDir` with `VCInstallDir` or `VCToolsVersion` – I'm not sure, if this do the trick. I think it's more correct to check if everything was installed during Visual Studio installation. 

As for me, I had no VS prompt at the beginning, but Studio. I just started installation process once again, and checked some components to install. It's appeared, that I had no ucrt component. Also, prompt appeared after second installation of Studio. And I'm not sure what component of installation responsible :(
